export const LINES_OF_BUSINESS = [
  "Commercial Package",
  "Auto (Commercial)",
  "Auto (Personal)",
  "Bond",
  "Business Owners",
  "Commercial Property",
  "Comprehensive Personal Liability",
  "Condominium",
  "Crime",
  "Cyber Liability",
  "Directors and Officers",
  "Dwelling Fire",
  "Equipment Breakdown",
  "Errors & Emissions",
  "Event Liability",
  "Excess Flood",
  "Excess Liability",
  "Fine Arts",
  "Jewelry",
  "Flood",
  "Garage & Dealers",
  "General Liability",
  "Homeowners",
  "Inland Marine (Commercial)",
  "Inland Marine (Personal)",
  "Builders Risk",
  "Liability Gap",
  "Specialty a la Carte Homeowners Coverages",
  "Lessor's Risk",
  "Liquor Liability",
  "Malpractice",
  "Miscellaneous Professional Liability",
  "Mobile Home",
  "Motorcycle",
  "Motor Truck Cargo",
  "Ocean Marine (Commercial)",
  "Notary Bond",
  "Renters / HO4",
  "Truckers",
  "Umbrella (Commercial)",
  "Umbrella (Personal)",
  "Vacant Property",
  "Wind Only Policy",
  "Workers Compensation",
  "Scheduled Watches Policy",
  "Travel Trailer",
  "Watercraft (Small Boat)",
  "Yacht"
];

// Compile-time or load-time length safety check
if (LINES_OF_BUSINESS.length !== 48) {
  throw new Error(`Lines of Business array must contain exactly 48 options. Current length: ${LINES_OF_BUSINESS.length}`);
}
